apiVersion: v1
kind: Service
metadata:
  name: {{ include "adservice.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adservice.labels" . | nindent 4 }}
    env: prod
spec:
  type: {{ .Values.service.type }}
  selector:
    app: 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9555
      name: grpc
  selector:
    {{- include "adservice.selectorLabels" . | nindent 4 }}
